### ISSUE TITLE
Curl errors handling

### ISSUE THREAD

**Issue by tomasced** [conversionxl/woocommerce-subscriptions-api-export#24]
`wp cxl shop-subscription-export-chartmogul --id=1043993` returned this error:

`Fatal error: Uncaught TypeError: Argument 1 passed to ChartMogul\Http\Client::handleResponse() must be an instance of Psr\Http\Message\ResponseInterface, null given, called in cxl-wpstarter\public\wp-content\plugins\woocommerce-subscriptions-api-export-trunk\vendor\chartmogul\chartmogul-php\src\Http\Client.php on line 164 and defined in cxl-wpstarter\public\wp-content\plugins\woocommerce-subscriptions-api-export-trunk\vendor\chartmogul\chartmogul-php\src\Http\Client.php:203`

Tried to debug what is happening. Edited **guzzlehttp/guzzle/src/Handler/CurlFactory.php** function **createRejection** and printed to console the error message:

`cURL error 60: SSL certificate problem: self signed certificate in certificate chain`

Modified **CurlFactory.php** function **create**. Added **CURLOPT_CAINFO**:

`curl_setopt($easy->handle, CURLOPT_CAINFO, "PATH_TO_CACERT.PEM"); `

The plugin started working.

**Q:** If curl returns any error, we won't know. Is there an easy way to handle curl errors or log them somewhere?

**Comment by umeshghediya** [comment]
guzzlehttp/guzzle/src/Handler/CurlFactory.php

I don't think this code should be changed.

` Argument 1 passed to ChartMogul\Http\Client::handleResponse() must be an instance of Psr\Http\Message\ResponseInterface
`

In which case argument 1 was not ResponseInterface type object.

**Comment by saas786** [comment]
Updated readme to overcome this issue: https://github.com/saas786/woocommerce-subscriptions-api-export/blob/syed/cm/phase2-c/README.md#local-server-wamp-or-similar-local-servers
