### ISSUE TITLE
Replace `Query` component with REST API endpoint

### ISSUE THREAD

**Issue by pawelkmpt** [conversionxl/woocommerce-subscriptions-api-export#29]
Currently it's possible to trigger export by visiting URL with relevant params, eg.: `https://cxl.com/institute/?shop-export-to-chartmogul=true&subscription-id=25&data-source=xxxxxx`

This operation does not do any authentication check which is a security risk.

I think the best would be to create REST API endpoint which would check auth. From the client perspective WordPress Application Passwords can be used.

**Comment by saas786** [comment]
Replaced Query Component with Rest API routes: https://github.com/conversionxl/woocommerce-subscriptions-api-export/pull/35
