### ISSUE TITLE
Free trial is not detected

### ISSUE THREAD

**Issue by tomasced** [conversionxl/woocommerce-subscriptions-api-export#31]
**Subscription**: https://cxl.com/institute/wp-admin/post.php?post=3097639&action=edit

**Issue**: The customer tried a _free trial_ first, then ordered a monthly plan. However, when importing data to ChartMogul the _free trial_ is not detected. We are using this logic to detect _free trial_: https://github.com/conversionxl/institute-plugin/blob/master/src/Plugin/Integrations/WooCommerce/Subscriptions.php#L198

**Note**: this customer doesn't have a _free trial_ end date:
![image](https://user-images.githubusercontent.com/53396400/127446804-8e343407-117c-4781-b733-4004ad278efd.png)

**Q**: how we can detect _free trial_ for this customer?

**Comment by pawelkmpt** [comment]
> **Q**: how we can detect _free trial_ for this customer?

My ideas:
* check subscription meta and how they change,
* check first order and its meta.

**Comment by kylebrodeur** [comment]
I've done something like this for popup maker conditionals. Check PUM
Intetegrations in cxl plug in.

**Comment by saas786** [comment]
> PUM / Popup Maker integration: https://github.com/conversionxl/institute-plugin/blob/1d96f52420b865e443425004ce36eb33000d777e/src/Plugin/Integrations/WPPopupMaker/Conditionals.php#L229

**Comment by saas786** [comment]
Implemented ref: https://github.com/saas786/woocommerce-subscriptions-api-export/commit/c35ce9f297fc72ceb45cff100f96c842654baaa9

Initially mistakenly was looking for active trials, so was not recording the none active trials. Now checking if user had a trial ragardless if its active or not.
