### ISSUE TITLE
Duplicate Action Scheduler requests

### ISSUE THREAD

**Issue by tomasced** [conversionxl/woocommerce-subscriptions-api-export#44]
Had a look at live imported data and found duplicate Action Scheduler requests, example:

![image](https://user-images.githubusercontent.com/53396400/132479696-7c5c2cb5-28a7-45b5-b66b-0590224b0eab.png)

Looks like it is not fetching the same data twice, but pending request takes space in AS table.

**Comment by saas786** [comment]
fixed in: https://github.com/conversionxl/woocommerce-subscriptions-api-export/pull/45

**Comment by saas786** [comment]
shipped in: https://github.com/conversionxl/woocommerce-subscriptions-api-export/commit/311c552eaa39e7acfcf4562b7754d408071b8e22
